### ISSUE TITLE
Question: is it possible to chain operations? 

### ISSUE THREAD

**Issue by DeanKamali** [devrafalko/exact-math#11]
Would be nice to chain oprations like so: 

`exactMath.add(5,5).round(result, 2);`

**Comment by devrafalko** [comment]
unfortunately not that way as the `exactMath` methods return primitive values `Number` or `String` rather than `exactMath` object itself. I'm planning to add the `chain` property to the config object that allows this feature but it requires to rebuild all the code. For now, if you want to have all calculations in one line, you can alternatively do it as follows:

    const e = import 'exact-math';
    const result = e.round(e.add(5, 5), 2);
